version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:edge-22.04
    steps:
      - checkout
      # Create build directory and build the project
      - run:
          name: Build the project
          command: |
            mkdir -p build
            cd build
            cmake ..
            cmake --build . --config Release
      # Persist the build artifacts to the workspace
      - persist_to_workspace:
          root: /home/circleci/project/build
          paths:
            - night

  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # Attach the workspace to access the built executable
      - attach_workspace:
          at: /home/circleci/project/build
      # Run the test script with the `night` executable as an argument
      - run:
          name: Run tests
          command: |
            cd tests
            bash test_night.sh /home/circleci/project/build/night

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
